name: pytest

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: mamba-org/setup-micromamba@v1
      with:
        generate-run-shell: true
        environment-file: envs/simvi.yml
    - run: |
        pytest --version
        pytest
      shell: micromamba-shell {0}
